[package]
name = "mp2c"
version = "0.1.0"
authors = ["Ameya Bhurke <ameyabhurke@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html