[package]
name = "mp2c"
version = "0.1.0"
authors = ["Ameya Bhurke <ameyabhurke@gmail.com>"]
edition = "2018"
license = "MIT"
description = "A multi producer multi polling consumer library that enables  multiple producers to send messages to multiple consumers completely asynchronously."